### ISSUE TITLE
Missing H3 File

### ISSUE THREAD

**Issue by DanTheMan827** [llakssz/FunKiiU#10]
I'm not familiar with python but relying on the content type being 0x2003 is wrong...

According to crediar the content type is a series of bit flags so the proper way is something like this

(c_type & 0x02) > 0

That's assuming that c_type was an integer and the bitwise operators are the same between python and c#...

**Comment by llakssz** [comment]
Yes that would work thanks :)
Initially I was just blindly getting them, then I tried to make it cleaner, but yeah I guess I did it wrong!
(c_type & 0x02) would be true for 2002 and 2003, and more values I guess too.
For now I'll just revert to blindly attempt each one.

Thanks
