### ISSUE TITLE
0005000010131d00 - japanese title, breaking program

### ISSUE THREAD

**Issue by llakssz** [llakssz/FunKiiU#25]
The folder is created fine (0005000010131d00 _ JPN _ 幻影異聞録_ＦＥ) but for this line, it breaks:

` print('-Downloading {}.\n-File size is {}.\n-File in disk is {}.'.format(outfname, expected_size,diskFilesize))`

`UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-50: character maps to <undefined>`

**Comment by dojafoja** [comment]
I sent a pull request to fix this

**Comment by llakssz** [comment]
Thanks @dojafoja
