### ISSUE TITLE
Add game title to downloaded folder name

### ISSUE THREAD

**Issue by PR0r** [llakssz/FunKiiU#4]
Is it possible to have the name of the game added to the folder name.
Currently just the Title ID is used.
eg. Name, Title ID

**Comment by llakssz** [comment]
https://github.com/llakssz/FunKiiU/pull/3

yes this should come soon :)

**Comment by llakssz** [comment]
It's done, if a name exists in the json file and you are using -onlinetickets/-onlinekeys, you will get a named folder within the 'install' directory.

I can add manual naming too, but not now.

**Comment by PR0r** [comment]
I'm getting an error as follows:

`user@server:~/Downloads/FunKiiU-master$ python FunKiiU.py -title 000500001012b200 -onlinetickets
*******
FunKiiU by cearp
*******

Downloading/updating data from wiiu.titlekeys.com
Downloaded data OK!
Family Party 30 Great Games Obstacle Arcade
Adventure Time Explore the  Dungeon Because I Don't Know!
Angry Birds Star Wars
Barbie Dreamhouse Party
Batman™ Arkham Origins
Darksiders II
DEUS EX HUMAN REV. DIRECTOR'S CUT
Traceback (most recent call last):
  File "FunKiiU.py", line 359, in <module>
    processTitleID(titleid, key)
TypeError: processTitleID() takes exactly 3 arguments (2 given)
user@server:~/Downloads/FunKiiU-master$ 
`

**Comment by llakssz** [comment]
oops... I thought I made sure it worked, I'll test again sorry...

**Comment by llakssz** [comment]
finished, it's in v2.0
