### ISSUE TITLE
Updated title key website website location

### ISSUE THREAD

**Issue by Spinoni31** [llakssz/FunKiiU#41]
Hello, since May 13 2017 the wii u "title key site" has moved to a different domain (instead of .com now is .gq), making the -onlinetickets and -onlinekeys functions broken. can it be resolved? if not, where do i need to modify the script so that it can find the new website?

Thanks in advance, Spinoni31.

**Comment by Nemris** [comment]
I can run the code with both `-onlinekeys` and `-onlinetickets` without issues. Are you using the latest version?

**Comment by Spinoni31** [comment]
Sorry, guess i was running a version that wasn't updated. got the script just now tried it and it worked.
thanks again, Spinoni31
