### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by TDC302** [llakssz/FunKiiU#43]
Im not exactly sure what this program is doing but I got the key and the name from -thekeysite- and figured out the command...
but even though im entering a semmingly valid command:
![image](https://user-images.githubusercontent.com/36140926/43553850-0f9c4714-95bf-11e8-8eed-980fdad33987.png)
![image](https://user-images.githubusercontent.com/36140926/43553829-f7e68774-95be-11e8-81ac-8ab31ff87956.png)
![image](https://user-images.githubusercontent.com/36140926/43553789-c2871b8e-95be-11e8-880d-cbacf74d6b1c.png)
It just comes up with errors.

**Comment by llakssz** [comment]
can you type 'python -V' for me? thanks

**Comment by dojafoja** [comment]
Are you typing these commands into a Python interpreter or are you typing them into a command prompt? If you're typing them into a Python interpreter, which I kind of think you are, that's your issue.

**Comment by UnicornsOnLSD** [comment]
You're writing the commands into IDLE, which is a Python interpreter. What you want to do is open command prompt, cd to where FunKiiU is, and then run the command you're using.
